version: 2
updates:
  - package-ecosystem: docker
    directories:
      - /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directories:
      - /
      - /frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 5
