version: 2

updates:
  - package-ecosystem: npm
    directories:
      - /
      - /frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directories:
      - /
    schedule:
      interval: daily
    open-pull-requests-limit: 0
