private: true

subPackages:
  - frontend

docker:
  build:
    defaultTag: latest
    autoTags: [main, latest, next]

docs:
  location: docs

  logo: true

  aliases:
    /api: https://raw.githubusercontent.com/softvisio-node/core/main/docs/api.md

  externalTypes:
    - softvisio-node/core
    - softvisio-node/result

  app:
    api:
      url: wss://localhost/api
    rpc:
      url: ws://localhost/api
