#!/usr/bin/env -S docker stack deploy --with-registry-auth playground -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml playground

services:
  playground:
    image: ghcr.io/zdm/playground
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 3

    command: ""

    configs:
      - { source: env.yaml, target: /var/local/package/env.yaml }

    networks: [main]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }

    build: .

configs:
  env.yaml: { file: env.yaml }

networks:
  main: { external: true }
