#!/usr/bin/env -S docker stack deploy --with-registry-auth playground -c

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml playground

version: "3.9"

services:
  playground:
    image: ghcr.io/zdm/playground
    depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 3

    command: run

    secrets:
      - { source: playground, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }

    build: .

secrets:
  playground: { file: env.yaml }

networks:
  network:
    name: ${DOCKER_STACK_NETWORK_NAME:-main}
    external: true
